# Generated by Django 5.2.14 on 2026-05-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Gejala',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='NilaiCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=100)),
                ('nama_sapi', models.CharField(blank=True, max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('gejala_dipilih', models.JSONField()),
                ('hasil_cf', models.JSONField()),
            ],
            options={
                'verbose_name': 'Hasil Konsultasi',
                'verbose_name_plural': 'Riwayat Konsultasi',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('solusi', models.TextField(help_text='Saran penanganan awal')),
            ],
            options={
                'verbose_name_plural': 'Penyakit',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_pakar', models.FloatField(help_text='Nilai CF dari pakar (0.0 – 1.0)')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.gejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.penyakit')),
            ],
            options={
                'verbose_name': 'Rule CF',
                'verbose_name_plural': 'Rule CF',
                'unique_together': {('penyakit', 'gejala')},
            },
        ),
    ]
