# Generated by Django 5.2.14 on 2026-06-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolusiPenanganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('pengobatan', 'Pengobatan'), ('pencegahan', 'Pencegahan'), ('manajemen', 'Manajemen Hewan'), ('sanitasi', 'Sanitasi & Biosecurity'), ('vaksinasi', 'Vaksinasi'), ('nutrisi', 'Nutrisi & Suplemen')], help_text='Jenis solusi penanganan', max_length=20)),
                ('judul', models.CharField(help_text='Judul singkat solusi', max_length=200)),
                ('deskripsi', models.TextField(help_text='Deskripsi lengkap solusi')),
                ('prioritas', models.IntegerField(default=1, help_text='Prioritas urutan tampil (1=tertinggi)')),
                ('aktif', models.BooleanField(default=True, help_text='Aktifkan solusi ini')),
                ('referensi', models.TextField(blank=True, help_text='Sumber referensi (opsional)')),
                ('catatan_khusus', models.TextField(blank=True, help_text='Catatan tambahan (opsional)')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diupdate', models.DateTimeField(auto_now=True)),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solusi_penanganan', to='core.penyakit')),
            ],
            options={
                'verbose_name': 'Solusi Penanganan',
                'verbose_name_plural': 'Solusi Penanganan',
                'ordering': ['penyakit__kode', 'prioritas', 'jenis'],
            },
        ),
    ]
